/* To find the total revenue generated by each employee */

SELECT first_name,count(unit_price) 
AS Totalrevenuegenerated
FROM order_details 
INNER JOIN orders
ON order_details.order_id= orders.order_id
INNER JOIN employees
ON orders.employee_id= employees.employee_id
GROUP BY first_name;